name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Publish GH-Pages Branch
    steps:
    - uses: actions/checkout@v2
    - name: Read .nvmrc
      run: echo "::set-output name=NODE_VERSION::$(cat .nvmrc)"
      id: node-read-version
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: "${{ steps.node-read-version.outputs.NODE_VERSION }}"
    - name: Install
      run: yarn install
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test --watchAll=false
    - name: Build
      run: yarn build
    - name: Publish
      env:
        GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        REPOSITORY_NAME: ${{ github.event.repository.name }}
      run: bash scripts/deploy-gh-pages.sh
